In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
# Fetch the data of titianic 
ti=pd.read_csv("titanic.csv")
ti.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [27]:
# To see the overall information about the dataset.
ti.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   str
 2   sex       1309 non-null   str
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   str
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    str
 9   embarked  1307 non-null   str
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), str(5)
memory usage: 112.6 KB

In [28]:
# To check the statistical information about the dataset.
ti.describe()

,pclass,age,sibsp,parch,fare,survived
count,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1309.000000
mean,2.294882,29.881135,0.498854,0.385027,33.295479,0.381971
std,0.837836,14.413500,1.041658,0.865560,51.758668,0.486055
min,1.000000,0.166700,0.000000,0.000000,0.000000,0.000000
25%,2.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,3.000000,39.000000,1.000000,0.000000,31.275000,1.000000
max,3.000000,80.000000,8.000000,9.000000,512.329200,1.000000

In [29]:
# To check how many null values are present in the dataset.
ti.isnull().sum()

pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

In [30]:
# To check how many duplicates values are present in the dataset.
ti.duplicated().sum()

np.int64(0)

First we handle the null values present in the dataset.

In [31]:
# Handle the null value of age column.
med=ti["age"].median()
ti["age"]=ti["age"].fillna(med)

In [32]:
# Now convert the datatype of the  age column 
ti["age"]=ti["age"].astype(int)
ti.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.5500,C22 C26,S,0

In [33]:
# Extract the surname and title of the  name column 

"""surname"""
ti["surname"]=ti["name"].str.split(",").str[0]

"""title"""
ti["title"]=ti["name"].str.split(",").str[1].str.split(".").str[0]

In [54]:
ti["fare"]=round(ti["fare"],2)

# Data Analysis

    
    How many passengers were aboard the Titanic?

In [34]:
# Total number of passengers.
ti["pclass"].count()

np.int64(1309)

In [35]:
# Number of survivors.
ti[ti["survived"]==1]["survived"].count()

np.int64(500)

In [36]:
# Number of non-survivors.
ti[ti["survived"]==0]["survived"].count()

np.int64(809)


    What was the overall survival rate?

In [37]:
surv=ti[ti["survived"]==1]["survived"].count()
total_pass=ti["survived"].count()

percentage=(surv/total_pass)*100

print(f"Percentage of overall survial rate : {round(percentage,2)}")

Percentage of overall survial rate : 38.2


    What was the distribution of passengers by sex?

In [38]:
# Number of male passengers.
ma=ti[ti["sex"]=="male"]["sex"].count()
print(f"Number of male passenger : {ma}")

Number of male passenger : 843

In [39]:
# Number of female passengers.
fe=ti[ti["sex"]=="female"]["sex"].count()
print(f"Number of female passenger : {fe}")

Number of female passenger : 466

In [40]:
# Percentage of each group.

male_percent=(ma/total_pass)*100
female_percent=(fe/total_pass)*100

# display(round(male_percent,2))
# display(round(female_percent,2))

print(f"Male percentage : {round(male_percent,2)}")
print(f"female percentage : {round(female_percent,2)}")

Male percentage : 64.4
female percentage : 35.6


    What was the distribution of passengers across ticket classes?
First-class passengers.  
Second-class passengers.  
Third-class passengers.

In [41]:
ti["pclass"].value_counts()

pclass
3    709
1    323
2    277
Name: count, dtype: int64


    What was the age distribution of passengers?

In [42]:
# Average age.
print(f"Average age of passenger : {round(ti["age"].mean(),2)}")

Average age of passenger : 29.48

In [43]:
# Median age.
print(f"Median age of passenger : {round(ti["age"].median(),2)}")

Median age of passenger : 28.0

In [44]:
# Youngest and oldest passengers.
print(f"Younger passenger : {round(ti["age"].min())}")
print(f"oldest passenger : {round(ti["age"].max())}")

Younger passenger : 0
oldest passenger : 80

    
    What was the distribution of ticket fares?

In [45]:
# Average fare.  
print(f"Average fare : {round(ti["fare"].mean(),2)}")

Average fare : 33.3

In [46]:
# Median fare.  
print(f"Median fare : {round(ti["fare"].median(),2)}")

Median fare : 14.45

In [47]:
# Minimum and maximum fares.  
print(f"Minimum fare : {round(ti["fare"].min(),2)}")
print(f"Maximum fare : {round(ti["fare"].max(),2)}")

Minimum fare : 0.0
Maximum fare : 512.33


    Did survival rates differ between male and female passengers?

In [61]:
# Male survival rate.
sur_mal=ti[(ti["sex"]=="male")&(ti["survived"]==1)]["survived"].count()
total_surv=ti[ti["survived"]==1]["survived"].count()

percent=(sur_mal/total_surv)*100

print(f"Male survival rate : {percent}")

Male survival rate : 32.2

In [65]:
# Female survival rate.
sur_fem=ti[(ti["sex"]=="female")&(ti["survived"]==1)]["survived"].count()
total_surv=ti[ti["survived"]==1]["survived"].count()

percent=(sur_fem/total_surv)*100
print(f"Female survival rate : {round(percent,2)} ")

Female survival rate : 67.8

In [68]:
# Number of survivors in each group.
ti[ti["survived"]==1]["sex"].value_counts()

sex
female    339
male      161
Name: count, dtype: int64

Export the data into mysql server :

In [69]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

In [70]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Aman987@",
    database="TITANIC"
)

print(" CONNECTION SUCCESSFULL")

 CONNECTION SUCCESSFULL

In [71]:
host="localhost"
user="root"
password=quote_plus("Aman987@")
database="TITANIC"
url=f"mysql+pymysql://{user}:{password}@{host}/{database}"
print(url)

# df=pd.read_csv("CSB.csv")
engine=create_engine(f"mysql+pymysql://{user}:{password}@{host}/{database}")
# import data 
ti.to_sql(
    name="ti",
    con=engine,
    if_exists="replace",
    index=False
)

print("You data is imported successfully.")

mysql+pymysql://root:Aman987%40@localhost/TITANIC
You data is imported successfully.